services:
  frontend:
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    volumes:
      - ./client:/app  # Mount your source code
      - node_modules_frontend:/app/node_modules # Use a named volume for node_modules
    command: npm run dev -- --host 0.0.0.0
    depends_on:
      - backend
      - python-service

  backend:
    build:
      context: ./server-express
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./server-express:/app
      - node_modules_backend:/app/node_modules # Same for backend
    environment:
      NODE_ENV: development
    command: npx nodemon server.js

  python-service:
    build:
      context: ./server-flask
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    volumes:
      - ./server-flask:/app
    command: flask run --host=0.0.0.0 --reload

volumes: # Define your named volumes here
  node_modules_frontend:
  node_modules_backend: